import java.sql.*;

import com.codeup.adlister.dao.Config;
import com.mysql.cj.jdbc.Driver;

import java.util.ArrayList;
import java.util.List;

public class MySQLAdsDao implements Ads {
    private Connection connection = null;


    //accepts Config class to obtain credentials
    public MySQLAdsDao(Config config) {
        try {
            //Connect to DB
            DriverManager.registerDriver(new Driver());
            connection = DriverManager.getConnection(
                    config.getUrl(),
                    config.getUser(),
                    config.getPassword()
            //Connect to DB
            );
        } catch (SQLException e) {
            throw new RuntimeException("Error connecting to the database!", e);
        }
    }


    @Override
    public List<Ad> all() {
        //List to store ads as ad objects
        List<Ad> ads = new ArrayList<>();

        try {
            //create statement object using connection object
            Statement statement = connection.createStatement();
            //Save SQL command in ResultSet rs
            ResultSet rs = statement.executeQuery("SELECT * FROM ads");
            //if there is another row, create new ad using elements
            while (rs.next()){
                Ad ad = new Ad(
                        rs.getLong("id"),
                        rs.getLong("user_id"),
                        rs.getString("title"),
                        rs.getString("description")
                );
                //add new ad object to list of ads
                ads.add(ad);
            }
        } catch (SQLException sqle){
            throw new RuntimeException("error connecting to db", sqle);
        }
        //return entire list of ads
        return ads;
    }

    @Override
    public Long insert(Ad ad) {
        //retrieve ad title
        String title = ad.getTitle();
        //retrieve ad description
        String description = ad.getDescription();
        //Structure of SQL query to be used
        String query = "INSERT INTO ads (user_id, title, description) VALUES (1, '" + title + "', '" + description + "')";
        try {
            //create statement object for SQL query
            Statement statement = connection.createStatement();
            //gain access to ids(primary keys) autogenerated by DB
            statement.executeUpdate(query, Statement.RETURN_GENERATED_KEYS);
            //holds ids generated by DB
            ResultSet rs = statement.getGeneratedKeys();
            //iterates through results
            rs.next();
            //retrieve generated id, 1 shows we want first result
            long key = rs.getLong(1);
            System.out.println("The key of the new insert is: " + key);
            return key;
        } catch (SQLException sqle){
            throw new RuntimeException("error connecting to db", sqle);
        }
    }
}